spring:
  application:
    name: url-shortener

  data:
    mongodb:
      auto-index-creation: true

  cache:
    type: redis
    redis:
      time-to-live: PT24H
    cache-names:
      - shortify

logging:
  level:
    root: INFO

---
spring:
  profiles: kubernetes

  cache:
    type: redis
