apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener
  namespace: ycb-local
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: url-shortener-role
  namespace: ycb-local
rules:
  - apiGroups:
      - ""
    resources:
      ["*"]
    verbs:
      ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: url-shortener-role-binding
  namespace: ycb-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: url-shortener-role
subjects:
  - kind: ServiceAccount
    name: url-shortener
    namespace: ycb-local